/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#2a2a2a',
        'error': '#f87171',
        'surface-container-low': '#161616', // Card Background
        'primary-fixed': '#10b981',
        'surface-container-highest': '#2c2c2c',
        'on-tertiary-fixed-variant': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-primary': '#000000',
        'surface-variant': '#1c1c1c',
        'primary-container': '#064e3b',
        'primary-fixed-dim': '#059669',
        'on-primary-container': '#d1fae5',
        'tertiary-fixed': '#ffffff',
        'surface-container': '#1c1c1c', // Accent Surface
        'surface-container-lowest': '#050505', // Deep Background
        'surface-bright': '#121212',
        'outline-variant': '#2c2c2c',
        'on-error-container': '#ffffff',
        'on-tertiary-fixed': '#000000',
        'inverse-surface': '#ffffff',
        'outline': '#444444',
        'on-secondary': '#000000',
        'secondary-fixed-dim': '#ffffff',
        'inverse-on-surface': '#000000',
        'inverse-primary': '#10b981',
        'on-secondary-fixed-variant': '#ffffff',
        'secondary': '#ffffff',
        'primary': '#10b981',
        'surface-dim': '#080808',
        'secondary-container': '#1c1c1c',
        'on-surface': '#ffffff',
        'surface-tint': '#10b981',
        'surface': '#0c0c0c',
        'on-surface-variant': '#ffffff',
        'error-container': '#7f1d1d',
        'surface-container-high': '#222222',
        'on-secondary-fixed': '#000000',
        'tertiary-fixed-dim': '#ffffff',
        'on-secondary-container': '#ffffff',
        'on-primary-fixed-variant': '#064e3b',
        'on-background': '#ffffff',
        'tertiary': '#ffffff',
        'on-tertiary-container': '#000000',
        'secondary-fixed': '#ffffff',
        'on-primary-fixed': '#000000',
        'background': '#0c0c0c',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
