/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#dde3eb',
        'error': '#ba1a1a',
        'surface-container-low': '#f0f1f2',
        'primary-fixed': '#000000',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-fixed-variant': '#dde3eb',
        'on-error': '#ffffff',
        'on-tertiary': '#dde3eb',
        'on-primary': '#e2e2e2',
        'surface-variant': '#e1e3e4',
        'primary-container': '#3b3b3b',
        'primary-fixed-dim': '#474747',
        'on-primary-container': '#ffffff',
        'tertiary-fixed': '#595f66',
        'surface-container': '#edeeef',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f8f9fa',
        'outline-variant': '#c6c6c6',
        'on-error-container': '#410002',
        'on-tertiary-fixed': '#ffffff',
        'inverse-surface': '#2e3132',
        'outline': '#777777',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#a0acc1',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#c6c6c6',
        'on-secondary-fixed-variant': '#313c4e',
        'secondary': '#545f72',
        'primary': '#000000',
        'surface-dim': '#d9dadb',
        'secondary-container': '#cad5ec',
        'on-surface': '#191c1d',
        'surface-tint': '#5e5e5e',
        'surface': '#f8f9fa',
        'on-surface-variant': '#474747',
        'error-container': '#ffdad6',
        'surface-container-high': '#e7e8e9',
        'on-secondary-fixed': '#111c2c',
        'tertiary-fixed-dim': '#41474e',
        'on-secondary-container': '#111c2c',
        'on-primary-fixed-variant': '#e2e2e2',
        'on-background': '#191c1d',
        'tertiary': '#363c42',
        'on-tertiary-container': '#ffffff',
        'secondary-fixed': '#bcc7dd',
        'on-primary-fixed': '#ffffff',
        'background': '#f8f9fa',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
